line-notify:
    personal-access-token: your_personal_access_token
    endpoint-uri: https://notify-api.line.me/api/notify
    data-path: data.json
    mustache-template-path: message-template/

plugins:
  line-notify:
    github:
      event-types:
        - create
        - issues
        - issue_comment
        - pull_request
        - pull_request_review
        - pull_request_review_comment
        - release
server:
  port: 8080

management:
  port: 28081
  add-application-context-header: false
  context-path: /spring-actuator

spring:
  freemarker:
    charset: UTF-8
    cache: false
    settings:
      template_exception_handler: rethrow
      default_encoding: UTF-8
  datasource:
    hikari:
      driver-class-name: org.h2.jdbcx.JdbcDataSource
      jdbc-url: jdbc:h2:file:/tmp/lng.h2db;MODE=MYSQL;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS "public"
      username: sa
      password:
      connection-timeout: 3000

mybatis:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

