line-notify:
    personal-access-token: your_personal_access_token
    endpoint-uri: https://notify-api.line.me/api/notify
    data-path: data.json
    mustache-template-path: message-template/

plugins:
  line-notify:
    github:
      event-types:
        - create
        - issues
        - issue_comment
        - pull_request
        - pull_request_review
        - pull_request_review_comment
        - release
server:
  port: 18081

management:
  port: 28081
  add-application-context-header: false
  context-path: /management

spring:
  freemarker:
    charset: UTF-8
    cache: false
    settings:
      template_exception_handler: rethrow
      default_encoding: UTF-8


